/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DroughtsRouteImport } from './routes/droughts'
import { Route as IndexRouteImport } from './routes/index'

const DroughtsRoute = DroughtsRouteImport.update({
  id: '/droughts',
  path: '/droughts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/droughts': typeof DroughtsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/droughts': typeof DroughtsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/droughts': typeof DroughtsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/droughts'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/droughts'
  id: '__root__' | '/' | '/droughts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DroughtsRoute: typeof DroughtsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/droughts': {
      id: '/droughts'
      path: '/droughts'
      fullPath: '/droughts'
      preLoaderRoute: typeof DroughtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DroughtsRoute: DroughtsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
